use_frameworks!

platform :ios, '9.0'

target 'BlueIntentBase_Example' do
  pod 'BlueIntentBase', :path => '../'

  target 'BlueIntentBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
