# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift # or objective-c

os: osx
osx_image: xcode11.2

xcode_workspace: Example/BlueIntentBase.xcworkspace
xcode_scheme: BlueIntentBase-Example
xcode_destination: platform=iOS Simulator,name=iPhone 8,OS=13.2.2

cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild -workspace Example/BlueIntentBase.xcworkspace -scheme BlueIntentBase-Example -destination platform\=iOS\ Simulator,name\=iPhone\ 8,OS\=13.2.2 build test | xcpretty
  - pod lib lint
